### ISSUE TITLE
Exception trying to divide BigDecimal by a number

### ISSUE THREAD

**Issue by QuantumDeveloper** [deveel/deveel-math#3]
Hi,
I was testing your lib and faced with exception: Non-terminating decimal expansion; no exact representable decimal result.

I was trying to do the following:

```
BigDecimal bigDecimal = BigDecimal.Parse("45465464646546546464646446547777777777777777777777777777888888888888888888888888888888777777777778542222222222221333333335");
         bigDecimal /= 700;
         MessageBox.Show(bigDecimal);
```

I expect thta it must return decimal result as a string, but it throws an exception instead.

Could this be fixed?

**Comment by tsutomi** [comment]
Hi @QuantumDeveloper 

Thank you for the report: I'm opening a test case to verify the error and fix it.

**Comment by QuantumDeveloper** [comment]
@tsutomi welcome. 
Will you fix this issue soon?

**Comment by tsutomi** [comment]
I already found a solution, working on the precision of the Divide operation (applying the precision of the first dividend): I'm verifying the result to be coherent, using different calculators

**Comment by tsutomi** [comment]
The issue was fixed. It will be available in the next version of the library from NuGet
