### ISSUE TITLE
BigInteger operators > and < swapped

### ISSUE THREAD

**Issue by giulianodianda** [deveel/deveel-math#6]
Hi,
Biginteger  > < operators are returning the opposite
https://github.com/deveel/deveel-math/blob/master/src/Deveel.Math/Deveel.Math/BigInteger.cs#L1765

should be: return a.CompareTo(b) > 0;

**Comment by tsutomi** [comment]
Thanks for the report @giulianodianda : I will fix it as soon as possible.

**Comment by tsutomi** [comment]
The fix was applied and tested
